# Numpy
- NumPy is a fundamental library for scientific computing in Pyhton. It provides support for `arrays` and `matrices`, along with a collection of mathematical function to operate on these data structures.
- In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [4]:
!pip install numpy

In [5]:
import numpy as np

## Create array using numpy
### Create 1D array

In [6]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)
print(arr1.argmax())

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
4


## 1D Array

In [7]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [8]:
print(arr2.shape)
print(type(arr2))
print(arr2)

(5,)
<class 'numpy.ndarray'>
[1 2 3 4 5]


## 2D Array

In [9]:
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [10]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## identity matrix

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
## Attributes of Numpy Array

In [14]:
arr = np.array([[1,2,3], [4,5,6]])
print("Array:\n", arr)
print("Shape", arr.shape)
print("Number of Dimensions: ", arr.ndim)
print("Size(Number of elements): ", arr.size)
print("Data type: ", arr.dtype)
print("Item size in bytes: ", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape (2, 3)
Number of Dimensions:  2
Size(Number of elements):  6
Data type:  int32
Item size in bytes:  4


## Numpy Vectorized Operation

In [15]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#### Elementwise Addition
print(f"Addition: ", arr1 + arr2)

#### Elementwise Substraction
print("Substraction: ", arr1-arr2)

#### Elementwise Multiplication
print("Multiplication: ", arr1 * arr2)

#### Elementwise Division
print("Multiplication: ", arr1 / arr2)

Addition:  [11 22 33 44 55]
Substraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Multiplication:  [0.1 0.1 0.1 0.1 0.1]


In [16]:
## Universal Function
arr = np.array([2,3,4,5,6])
## square root
print("Square root: \n", np.sqrt(arr))

## Exponential
print(f"Exponentioal: \n{np.exp(arr)}")

## sine
print(f"sine:\n {np.sin(arr)}")

## cose
print(f"cos: \n {np.cos(arr)}")

## Natural Log
print(f"Log: \n {np.log(arr)}")


Square root: 
 [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponentioal: 
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
sine:
 [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
cos: 
 [-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029]
Log: 
 [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


## array sclicing and Indexing

In [17]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array: \n", arr)
print("dimensions: ", arr.ndim)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
dimensions:  2


In [18]:
arr[0]

array([1, 2, 3, 4])

In [19]:
arr[0][0]

1

In [20]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
arr[1:2]

array([[5, 6, 7, 8]])

In [23]:
print(arr[0][0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [24]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
print(arr[1:3,1:3])
print(arr[0:, 1:3])

[[ 6  7]
 [10 11]]
[[ 2  3]
 [ 6  7]
 [10 11]]


In [26]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
# 5,6,
# 9,10

print(arr[1:, :2])

[[ 5  6]
 [ 9 10]]


## Modify array elements

In [28]:
arr[0,2] = 5
arr

array([[ 1,  2,  5,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
arr[0:1] = 100
print(arr)

[[100 100 100 100]
 [  5   6   7   8]
 [  9  10  11  12]]


In [30]:
arr[0:1] = 1, 2, 3, 4
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 3D Array

In [31]:
arr = np.array([[[1,2,3,4]], [[5,6,7,8]], [[9,10,11,12]]])
print("Array: \n", arr)
print("dimensions: ", arr.ndim)

Array: 
 [[[ 1  2  3  4]]

 [[ 5  6  7  8]]

 [[ 9 10 11 12]]]
dimensions:  3


### Statical concepts -- Normalization

In [32]:
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

# Calculate the mean and Standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data-mean) / std_dev
print("Normalized data: \n", normalized_data)

Normalized data: 
 [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [33]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
print(f"Mean = {np.mean(data)}")

# Median
print(f"Median: {np.median(data)}")

# Standard Deviation
print(f"SD: {np.std(data)}")

# variance
print(f"variance: {np.var(data)}")



Mean = 5.5
Median: 5.5
SD: 2.8722813232690143
variance: 8.25


### Logical Operations

In [34]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [37]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [47]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data > 5) & (data <= 8)]      # `and` this not works here `&` this logical works here


array([6, 7, 8])

In [48]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data > 5) | (data <= 8)]  

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])