# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [1]:
#1
import numpy as np
arr = np.random.randint(1,21,size=(5,5))
arr

arr[:, 2] = 1
print("Modified array:")
print(arr)

Modified array:
[[ 8 15  1  3 16]
 [ 2 19  1  2  7]
 [17  2  1  4  9]
 [ 9 18  1  1 13]
 [12 18  1 10 17]]


In [2]:
arr2 = np.arange(1,17).reshape(4,4)
print(arr2)

np.fill_diagonal(arr2,0)
arr2


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [3]:
# 1 
arr1 = np.random.randint(1,11,size=(3,4))
arr2 = np.random.randint(1,11,size=(3,4))

print("arr1: ", arr1)
print("arr2: ", arr2)

# Perform element-wise operations
addition = arr1 + arr2
subtraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

arr1:  [[ 3  8 10  9]
 [ 4  4  6  8]
 [ 4  2  7  8]]
arr2:  [[ 4  1 10  6]
 [ 8  1  5  4]
 [10  5  9  9]]
Element-wise addition:
[[ 7  9 20 15]
 [12  5 11 12]
 [14  7 16 17]]
Element-wise subtraction:
[[-1  7  0  3]
 [-4  3  1  4]
 [-6 -3 -2 -1]]
Element-wise multiplication:
[[ 12   8 100  54]
 [ 32   4  30  32]
 [ 40  10  63  72]]
Element-wise division:
[[0.75       8.         1.         1.5       ]
 [0.5        4.         1.2        2.        ]
 [0.4        0.4        0.77777778 0.88888889]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [4]:
array = np.arange(1, 17).reshape((4, 4))
print("Original array:")
print(array)

row_sum = np.sum(array, axis=1)
column_sum = np.sum(array, axis=0)
print("row wise sum: ",row_sum)
print("column wise sum: ",column_sum)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
row wise sum:  [10 26 42 58]
column wise sum:  [28 32 36 40]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [5]:
# 1: 
arr = np.random.randint(1,21, size=(5,5))
print(arr)

print("Mean: ", np.mean(arr))
print("Median: ", np.median(arr))
print("std: ", np.std(arr))
print("variance: ", np.var(arr))

[[ 6 19  2 20 15]
 [19 15  6 14 19]
 [ 8 17  1 14 19]
 [12  9 11  8 16]
 [11  4 18 11  8]]
Mean:  12.08
Median:  12.0
std:  5.585123096226259
variance:  31.1936


2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [6]:
arr = np.arange(1,10).reshape(3,3)
print(arr)

# Normalize the array
mean = np.mean(array)
std_dev = np.std(array)
normalize = (arr - mean) / std_dev
print("Normalize: ", normalize)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Normalize:  [[-1.62697843 -1.41004798 -1.19311752]
 [-0.97618706 -0.7592566  -0.54232614]
 [-0.32539569 -0.10846523  0.10846523]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [9]:
array = np.random.randint(1,21,size=(3,3))
print("2D Array: ")
print(array)

one_D_Array = np.random.randint(1,21, size=(3,))
print("1D Array: ")
print(one_D_Array)

print("Addition using Broadcasting: ")
print(array+one_D_Array)

2D Array: 
[[20  5  1]
 [15  4 12]
 [14  4  9]]
1D Array: 
[12  8  8]
Addition using Broadcasting: 
[[32 13  9]
 [27 12 20]
 [26 12 17]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
array = np.random.randint(1,21, size=(4,4))
one_D_Array = np.random.randint(1,21, size=(4,))
print(f"Array = {array}")
print(f"1D Array = {one_D_Array}")

print(f"Substracting 1D from 2D = {array - one_D_Array[:, np.newaxis]}")

Array = [[13 11 18  5]
 [19 18  1  7]
 [12  1  4 10]
 [15  8  7 16]]
1D Array = [12  9 10  7]
Substracting 1D from 2D = [[ 1 -1  6 -7]
 [10  9 -8 -2]
 [ 2 -9 -6  0]
 [ 8  1  0  9]]


In [15]:
one_D_Array[:,np.newaxis]

array([[12],
       [ 9],
       [10],
       [ 7]], dtype=int32)

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [19]:
# Create a NumPy array of shape (3, 3) representing a matrix
matrix = np.random.randint(1, 11, size=(3, 3))
print("Original matrix:")
print(matrix)

determinant = np.linalg.det(matrix)
print("Determinant: ", determinant)

inverse = np.linalg.inv(matrix)
print("inverse: ", inverse)

eigenvalues = np.linalg.eigvals(matrix)
print("eigenvalues: ", eigenvalues)

Original matrix:
[[ 8  3  3]
 [ 4  5 10]
 [ 3  1 10]]
Determinant:  256.99999999999983
inverse:  [[ 0.15564202 -0.10505837  0.05836576]
 [-0.03891051  0.27626459 -0.26459144]
 [-0.04280156  0.00389105  0.10894942]]
eigenvalues:  [14.7644555 +0.j          4.11777225+0.67128338j  4.11777225-0.67128338j]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [23]:
arr1 = np.random.randint(1,21,size=(2,3))
arr2 = np.random.randint(1,21,size=(3,2))

print("Array 1: ")
print(arr1)
print("Array 2: ")
print(arr2)

print("Matix Multiplication: ",np.dot(arr1,arr2))

Array 1: 
[[ 9  2 15]
 [ 4  2  1]]
Array 2: 
[[ 2 15]
 [ 3  4]
 [16  7]]
Matix Multiplication:  [[264 248]
 [ 30  75]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [33]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
array = np.arange(1, 10).reshape(3, 3)
print("Original array:")
print(array)
print(array.ndim)

# Reshape the array to shape (1, 9)
reshaped_array_1 = array.reshape((1, 9))
print("Reshaped array (1, 9):")
print(reshaped_array_1)

# Reshape the array to shape (9, 1)
reshaped_array_2 = reshaped_array_1.reshape((9, 1))
print("Reshaped array (9, 1):")
print(reshaped_array_2)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
Reshaped array (1, 9):
[[1 2 3 4 5 6 7 8 9]]
Reshaped array (9, 1):
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [36]:
array = np.random.randint(1,21,size=(5,5))
print("Original Array: ", array)

flatten_array = array.flatten()
print(flatten_array)

reshaped_array = flatten_array.reshape(5,5)
print(reshaped_array)

Original Array:  [[19  6  5  1  6]
 [15 10 14  7 16]
 [12  1  9 20  4]
 [13 17 18 12 12]
 [10 16 12 10 12]]
[19  6  5  1  6 15 10 14  7 16 12  1  9 20  4 13 17 18 12 12 10 16 12 10
 12]
[[19  6  5  1  6]
 [15 10 14  7 16]
 [12  1  9 20  4]
 [13 17 18 12 12]
 [10 16 12 10 12]]


### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [43]:
arr = np.random.randint(1,21,size=(5,5))
print(arr)
print(arr[0][0])
print(arr[0][-1])
print(arr[-1][0])
print(arr[-1][-1])


[[14  7  3  2  6]
 [ 6 14  4  5 15]
 [12  7  4 15 18]
 [20 14 12  6  7]
 [20  3 16  3 16]]
14
6
20
16


In [44]:
# Create a NumPy array of shape (5, 5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

# Use fancy indexing to extract the elements at the corners of the array
corners = array[[0, 0, -1, -1], [0, -1, 0, -1]]
print("Corner elements:")
print(corners)

Original array:
[[20 18  4 11  7]
 [13  4 11 10 18]
 [ 7 15 19  7 16]
 [ 7  5  5  1  2]
 [ 9 16 13  7 17]]
Corner elements:
[20  7  9 17]


2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [49]:
arr = np.random.randint(1,21,size=(4,4))

arr[arr>10] = 10
print(arr)

[[10  1  8  6]
 [10  8  6 10]
 [ 9  6  1  9]
 [ 6  1  7 10]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [50]:
data_type = [("name","U10"), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [51]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [53]:
import numpy.ma as ma
arr = np.random.randint(1, 21, size=(4, 4))
masked_arr = ma.masked_greater(arr,10)
print(arr)
print(masked_arr)

[[ 8 17 12  8]
 [15  2 18  7]
 [ 6  5 10  1]
 [ 5 17 16  6]]
[[8 -- -- 8]
 [-- 2 -- 7]
 [6 5 10 1]
 [5 -- -- 6]]


In [52]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array = ma.masked_greater(array, 10)
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Compute the sum of the unmasked elements
sum_unmasked = masked_array.sum()
print("Sum of unmasked elements:", sum_unmasked)

Original array:
[[ 9 18 14 16]
 [ 4  7 10 19]
 [10 19 18 10]
 [15 19 15 19]]
Masked array:
[[9 -- -- --]
 [4 7 10 --]
 [10 -- -- 10]
 [-- -- -- --]]
Sum of unmasked elements: 50


2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [56]:
array = np.random.randint(1,21, size=(3,3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[ 6 17 10]
 [ 4 18 17]
 [13  4 15]]
Masked array:
[[-- 17 10]
 [4 -- 17]
 [13 4 --]]
Modified masked array:
[[10 17 10]
 [ 4 10 17]
 [13  4 10]]


In [55]:
# Create a masked array of shape (3, 3) with random integers
array = np.random.randint(1, 21, size=(3, 3))
masked_array = ma.masked_array(array, mask=np.eye(3, dtype=bool))
print("Original array:")
print(array)
print("Masked array:")
print(masked_array)

# Replace the masked elements with the mean of the unmasked elements
mean_unmasked = masked_array.mean()
masked_array = masked_array.filled(mean_unmasked)
print("Modified masked array:")
print(masked_array)

Original array:
[[20  8 16]
 [16  3 18]
 [ 9 10  6]]
Masked array:
[[-- 8 16]
 [16 -- 18]
 [9 10 --]]
Modified masked array:
[[12  8 16]
 [16 12 18]
 [ 9 10 12]]
